name: condaenv-unichat
channels:
  - pytorch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/
  - conda-forge
  - defaults
dependencies:
  - aiohappyeyeballs=2.4.4
  - aiohttp=3.11.10
  - aiosignal=1.2.0
  - altgraph=0.17.3
  - annotated-types=0.6.0
  - anyio=4.6.2
  - async-timeout=4.0.3
  - attrs=24.3.0
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - certifi=2025.1.31
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - click=7.1.2
  - colorama=0.4.6
  - cryptography=44.0.1
  - cudatoolkit=11.8.0
  - cython=3.0.11
  - dataclasses-json=0.6.5
  - distro=1.9.0
  - dnspython=2.4.2
  - docx2txt=0.8
  - email-validator=2.2.0
  - email_validator=2.2.0
  - exceptiongroup=1.2.0
  - faiss=1.9.0
  - fastapi=0.112.1
  - fastapi-cli=0.0.7
  - frozenlist=1.5.0
  - greenlet=3.1.1
  - h11=0.14.0
  - httpcore=1.0.2
  - httptools=0.6.4
  - httpx=0.27.0
  - httpx-sse=0.4.0
  - idna=3.7
  - intel-openmp=2023.1.0
  - jinja2=3.1.6
  - jiter=0.6.1
  - jsonpatch=1.33
  - jsonpointer=2.1
  - langchain-text-splitters=0.3.3
  - langsmith=0.1.147
  - libblas=3.9.0
  - libfaiss=1.9.0
  - libffi=3.4.4
  - liblapack=3.9.0
  - libzlib=1.2.13
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markdown-it-py=2.2.0
  - markupsafe=3.0.2
  - marshmallow=3.19.0
  - mdurl=0.1.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - msys2-conda-epoch=20160418
  - multidict=6.1.0
  - mypy_extensions=1.0.0
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openssl=3.0.16
  - orjson=3.10.14
  - packaging=24.2
  - pefile=2023.2.7
  - pip=25.0
  - propcache=0.2.0
  - pycparser=2.21
  - pydantic-core=2.27.1
  - pygments=2.15.1
  - pyinstaller=6.6.0
  - pyinstaller-hooks-contrib=2025.1
  - pyjwt=2.10.1
  - pypandoc=1.15
  - pysocks=1.7.1
  - python=3.10.16
  - python-dotenv=0.21.0
  - python-multipart=0.0.9
  - python_abi=3.10
  - pywin32=308
  - pywin32-ctypes=0.2.2
  - pyyaml=6.0.2
  - regex=2024.11.6
  - requests=2.32.3
  - requests-toolbelt=1.0.0
  - rich=13.9.4
  - rich-toolkit=0.11.3
  - setuptools=75.8.0
  - shellingham=1.5.0
  - sniffio=1.3.0
  - sqlalchemy=2.0.37
  - sqlite=3.45.3
  - starlette=0.38.2
  - tbb=2021.8.0
  - tenacity=8.2.3
  - tiktoken=0.9.0
  - tk=8.6.14
  - toml=0.10.2
  - tomlkit=0.13.2
  - tqdm=4.67.1
  - typer=0.15.2
  - typer-slim=0.15.2
  - typer-slim-standard=0.15.2
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_inspect=0.9.0
  - tzdata=2025a
  - ucrt=10.0.20348.0
  - urllib3=2.3.0
  - uvicorn=0.32.1
  - uvicorn-standard=0.32.1
  - vc=14.42
  - vc14_runtime=14.42.34438
  - vs2015_runtime=14.42.34438
  - watchfiles=0.24.0
  - websockets=10.4
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - xz=5.6.4
  - yaml=0.2.5
  - yarl=1.18.0
  - zlib=1.2.13
  - pip:
      - chardet==5.1.0
      - dashscope==1.22.1
      - langchain==0.3.20
      - langchain-community==0.3.20
      - langchain-core==0.3.46
      - langchain-deepseek==0.1.2
      - langchain-ollama==0.2.3
      - langchain-openai==0.3.9
      - ollama==0.4.7
      - openai==1.66.3
      - pandoc==2.4
      - pillow==11.2.0
      - pipe-subprocess==0.3.7
      - plumbum==1.9.0
      - ply==3.11
      - psutil==7.0.0
      - pydantic==2.9.2
      - pydantic-settings==2.8.1
      - pyinstaller-versionfile==3.0.0
      - pymupdf==1.25.4
      - pyqt5==5.15.5
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.17.0
      - urlparser==0.1.2
      - websocket-client==1.8.0
prefix: D:\ProgramData\anaconda3\envs\condaenv-unichat
