[Providers]
[Providers.OpenAI]
OPENAI_BASE_URL="https://api.openai.com/v1"
OPENAI_LLM_MODEL="gpt-4o-mini"
OPENAI_EMB_MODEL="text-embedding-ada-002"
[Providers.MoonShot]
MOONSHOT_BASE_URL="https://api.moonshot.cn/v1"
MOONSHOT_LLM_MODEL="moonshot-v1-8k"
MOONSHOT_EMB_MODEL=""
[Providers.Baichuan]
BAICHUAN_BASE_URL="https://api.baichuan-ai.com/v1"
BAICHUAN_LLM_MODEL="Baichuan3-Turbo"
BAICHUAN_EMB_MODEL="Baichuan-Text-Embedding"
[Providers.ZhipuAI]
ZHIPUAI_BASE_URL="https://open.bigmodel.cn/api/paas/v4/"
ZHIPUAI_LLM_MODEL="GLM-3-Turbo"
ZHIPUAI_EMB_MODEL="embedding-3"
[Providers.DeepSeek]
DEEPSEEK_BASE_URL="https://api.deepseek.com"
DEEPSEEK_LLM_MODEL="deepseek-chat"
DEEPSEEK_EMB_MODEL="Embedding-3"
[Providers.DashScope]
DASHSCOPE_BASE_URL="https://dashscope.aliyuncs.com/compatible-mode/v1"
DASHSCOPE_LLM_MODEL="qwen2-0.5b-instruct"
DASHSCOPE_EMB_MODEL=""
